services:
  enginar-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    image: tamerkucukel/enginar-frontend:latest
    container_name: enginar_frontend
    ports:
      - "3000:80"