name: Docker Deploy

on:
  workflow_dispatch:
    inputs:
      tag_version:
        type: string
        description: 'Type a tag version to be deployed to Docker Hub : (vX.X.X)'
        required: true
  push:
    tags:
     - v*

jobs:
  docker-build-push:
    if: ${{ startsWith(github.ref, 'refs/tags/') || inputs.tag_version != '' }}
    name: Docker Build and Push
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensures full clone for accurate analysis
        ref: ${{ inputs.tag_version || github.ref }}
    
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Generate Docker Tags
      id: docker_tags
      run: |
        if [[ -n "${{ inputs.tag_version }}" ]]; then
          echo "version=${{ inputs.tag_version }}" >> $GITHUB_OUTPUT
          echo "use_latest=false" >> $GITHUB_OUTPUT
        else
          VERSION="${GITHUB_REF##*/}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "use_latest=true" >> $GITHUB_OUTPUT
        fi

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        build-args: |
          VITE_API_BASE_URL=${{ vars.VITE_API_BASE_URL }}
        push: true
        tags: |
          tamerkucukel/enginar-frontend:${{ steps.docker_tags.outputs.version }}
          ${{ steps.docker_tags.outputs.use_latest == 'true' && 'tamerkucukel/enginar-frontend:latest' || '' }}
