name: Git Flow Control

on:
  pull_request:
    branches:
      - main
      - dev
      - 'release/**'
    types:
      - opened

jobs:
  git-flow-check:
    runs-on: self-hosted
    steps:
      - name: Check branch naming convention
        env:
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          # Define allowed patterns for base branches and head branches
          if [[ "$BASE_BRANCH" == "main" ]]; then
            ALLOWED_PATTERN="^(release|hotfix)\/.*$"
          elif [[ "$BASE_BRANCH" == "dev" ]]; then
            ALLOWED_PATTERN="^(feature|hotfix|release|bugfix)\/.*$"
          elif [[ "$BASE_BRANCH" =~ "^(release)\/.*$" ]]; then
            ALLOWED_PATTERN="^(hotfix\/.*|dev|bugfix\/.*)$"
          else
            echo "Error: Pull requests are only allowed to 'main', 'development', or 'release' branches."
            exit 1
          fi

          # Check if the head branch matches the allowed pattern
          if [[ ! "$HEAD_BRANCH" =~ $ALLOWED_PATTERN ]]; then
            echo "Error: Pull requests to '$BASE_BRANCH' can only come from branches matching '$ALLOWED_PATTERN'."
            exit 1
          fi

      - name: Success message
        if: success()
        run: echo "Pull request source branch is compliant with Git Flow."
